var Dashboard = {
    "id":null,
    "message":null,
    "title":null,
    "status":"0",
    "data":[
        {
            "content":{

            },
            "nodeId":221765,
            "type":"ZoomNode",
            "scaleX":1.0,
            "scaleY":1.0,
            "projectId":62,
            "children":[
                {
                    "content":{
                        "title":"VVM Improvement",
                        "typeOfWebview":null,
                        "zoomType":"kanban",
                        "weeklyActivities":[

                        ],
                        "displayOrder":0
                    },
                    "nodeId":898734,
                    "type":"ZoomNode",
                    "x":-1.0,
                    "y":-1.0,
                    "scaleX":0.2,
                    "scaleY":0.2,
                    "parentId":221765,
                    "projectId":62,
                    "children":[
                        {
                            "content":{

                            },
                            "nodeId":898735,
                            "type":"BacklogNode",
                            "x":10.0,
                            "y":2.0,
                            "width":420.0,
                            "height":1613.0,
                            "scaleX":1.0,
                            "scaleY":1.0,
                            "parentId":898734,
                            "projectId":62,
                            "children":[

                            ],
                            "zindex":"6"
                        },
                        {
                            "content":{
                                "stickyCode":"feature",
                                "escalationSourceProjectsId":[

                                ],
                                "aptmtId":null,
                                "belongOrganizedMode":null,
                                "linkedStickyNotesId":[

                                ],
                                "planningStageId":0,
                                "currentStatus":null,
                                "modifiedDate":null,
                                "escalatedProjectsId":[

                                ],
                                "id":2273689,
                                "values":[
                                    {
                                        "value":"CR: Distribution list",
                                        "type":"title"
                                    },
                                    {
                                        "value":"",
                                        "type":"description"
                                    },
                                    {
                                        "value":"1",
                                        "type":"consumed"
                                    },
                                    {
                                        "value":"4",
                                        "type":"todo"
                                    },
                                    {
                                        "value":"5",
                                        "type":"estimated"
                                    },
                                    {
                                        "value":"24/07/2015",
                                        "type":"date"
                                    },
                                    {
                                        "value":"98",
                                        "type":"stickyColor"
                                    },
                                    {
                                        "value":"35",
                                        "type":"featureDisk"
                                    },
                                    {
                                        "value":"haile",
                                        "type":"person"
                                    },
                                    {
                                        "value":"",
                                        "type":"id_task"
                                    },
                                    {
                                        "value":"",
                                        "type":"source"
                                    },
                                    {
                                        "value":"",
                                        "type":"zone_regroupement"
                                    }
                                ],
                                "description":null,
                                "colIndex":25,
                                "rowIndex":37,
                                "escalationNote":null,
                                "createDate":null
                            },
                            "nodeId":2273689,
                            "type":"StickyNoteNode",
                            "x":3648.8572,
                            "y":306.0,
                            "width":200.0,
                            "height":100.0,
                            "scaleX":1.0,
                            "scaleY":1.0,
                            "parentId":898734,
                            "projectId":62,
                            "children":[
                                {
                                    "content":{
                                        "aptmtId":null,
                                        "diskColor":"#B81A00",
                                        "description":null,
                                        "discTypeCode":null
                                    },
                                    "nodeId":2273690,
                                    "type":"DiskNode",
                                    "width":28.0,
                                    "height":28.0,
                                    "scaleX":1.0,
                                    "scaleY":1.0,
                                    "parentId":2273689,
                                    "projectId":62,
                                    "children":[

                                    ],
                                    "zindex":"15"
                                }
                            ],
                            "zindex":"15"
                        }
                    ],
                    "zindex":"5"
                }
            ],
            "zindex":"5"
        }
    ],
    "date":1437766118944
}